import {createCosmos} from './expedition-scene.js';
import {evidence,stages,sources,STORAGE_KEY,safeJournal,addEntry,journalMarkdown,stageIndex} from './expedition-data.js';

const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
let calm=motionQuery.matches,stage=stageIndex(location.hash.slice(1)),card=0,cosmos=null,journal=safeJournal(null),persist=false,storageError=false;
try{const saved=localStorage.getItem(STORAGE_KEY);if(saved){journal=safeJournal(JSON.parse(saved));persist=true;}}catch{storageError=true;}
$('#save-local').checked=persist;$('#reflection').value=journal.reflection;
function report(text){$('#scene-message').textContent=text;$('#scene-message').hidden=!text;}
function save(){
 $('#journal-count').textContent=journal.entries.length;
 if(persist){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(journal));storageError=false;}catch{storageError=true;}}
 $('#journal-status').textContent=storageError?'Bewaren op dit apparaat is niet beschikbaar. Download je logboek om het te bewaren.':persist?'Bewaard op dit apparaat.':'Alleen in deze sessie. Download of zet lokaal bewaren aan om het te behouden.';
}
function record(entry){journal=addEntry(journal,{...entry,time:new Date().toISOString()});save();renderJournal();}
function renderJournal(){
 const container=$('#journal-entries');container.replaceChildren();
 if(!journal.entries.length){const p=document.createElement('p');p.textContent='Nog geen waarnemingen toegevoegd. Bewaar onderweg een vondst die je wilt onthouden.';container.append(p);}
 for(const entry of journal.entries){const article=document.createElement('article');article.className='journal-card';const title=document.createElement('h3');title.textContent=entry.title;const copy=document.createElement('p');copy.textContent=entry.text;article.append(title,copy);if(entry.source){const link=document.createElement('a');link.href=entry.source;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Lees de bron ↗';article.append(link);}container.append(article);}
}
function openJournal(){renderJournal();save();$('#journal').showModal();}
$('#journal-open').onclick=openJournal;
$('#save-local').onchange=e=>{persist=e.target.checked;if(!persist){try{localStorage.removeItem(STORAGE_KEY);storageError=false;}catch{storageError=true;}}save();};
$('#save-note').onclick=()=>{journal.reflection=$('#reflection').value.slice(0,3000);save();};
$('#reflection').oninput=()=>{journal.reflection=$('#reflection').value.slice(0,3000);save();};
$('#export-notes').onclick=()=>{journal.reflection=$('#reflection').value.slice(0,3000);const url=URL.createObjectURL(new Blob([journalMarkdown(journal)],{type:'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='Voyager-mijn-logboek.md';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#clear-notes').onclick=()=>{if(!confirm('Je notities en bewaarde vondsten op dit apparaat wissen? Dit kun je niet ongedaan maken.'))return;journal=safeJournal(null);$('#reflection').value='';persist=false;$('#save-local').checked=false;try{localStorage.removeItem(STORAGE_KEY);storageError=false;}catch{storageError=true;}save();renderJournal();};
$('#source-list').innerHTML=sources.map(s=>`<div class="source"><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)} ↗</a><p>${escape(s.detail)}</p></div>`).join('');
$('#settings-open').onclick=()=>$('#settings').showModal();
function setCalm(value){calm=!!value;cosmos?.setCalm(calm);$('#calm').checked=calm;$('#quiet').setAttribute('aria-pressed',String(calm));$('#quiet').textContent=calm?'Rustige kijkmodus aan':'Rustige kijkmodus';}
$('#quiet').onclick=()=>setCalm(!calm);$('#calm').onchange=e=>setCalm(e.target.checked);motionQuery.addEventListener('change',e=>setCalm(e.matches));
$('#quality').onchange=e=>cosmos?.setQuality(e.target.value);
function immerse(value){document.body.classList.toggle('immersed',value);$('#hide-ui').setAttribute('aria-pressed',String(value));$('#restore-ui').hidden=!value;requestAnimationFrame(()=>{if(value)$('#restore-ui').focus();else $('#hide-ui').focus();});}
$('#hide-ui').onclick=()=>immerse(true);$('#restore-ui').onclick=()=>immerse(false);
addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]'))immerse(false);});
$('#reset-view').onclick=()=>cosmos?.reset();
// All information stays available when graphics are unavailable.
try{cosmos=createCosmos($('#cosmos'),{report,calm});}catch{report('3D is niet beschikbaar op dit apparaat. De vijf etappes, foto en bewijskaarten kun je wel hieronder bekijken.');}
setCalm(calm);save();
const zoomControls=document.createElement('div');zoomControls.className='zoom-controls';zoomControls.innerHTML='<button id="zoom-in" aria-label="Inzoomen">＋</button><button id="zoom-out" aria-label="Uitzoomen">−</button>';$('.scene-tools').append(zoomControls);$('#zoom-in').onclick=()=>cosmos?.zoom(.8);$('#zoom-out').onclick=()=>cosmos?.zoom(1.25);

function evidenceCard(){
 const e=evidence[card];$('#evidence-detail').innerHTML=`<article class="evidence-card"><small>${e.tag}</small><h3>${e.name}</h3><p><b>Waarneming</b><br>${e.measured}</p><p><b>Verklaring</b><br>${e.inferred}</p><p class="limit"><b>Grens van het bewijs</b><br>${e.limit}</p><a href="${e.source}" target="_blank" rel="noopener noreferrer">${e.sourceName} ↗</a></article><button id="save-evidence">Bewaar deze vondst</button><p class="micro" id="evidence-saved" role="status"></p>`;
 document.querySelectorAll('[data-evidence]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.evidence)===card)));
 $('#save-evidence').onclick=()=>{record({id:e.id,title:e.name,text:`Waarneming: ${e.measured}\nVerklaring: ${e.inferred}\nGrens: ${e.limit}`,source:e.source});$('#evidence-saved').textContent='Toegevoegd aan je logboek.';};
}
function setStage(value,updateHash=true){
 stage=stageIndex(value);const s=stages[stage];if(updateHash)history.replaceState(null,'',`#${stage}`);
 $('#scene-name').textContent=s.name;$('#scene-location').textContent=s.location;$('#chapter-counter').textContent=`0${stage+1} / 05 · ${s.chapter}`;$('#chapter-title').textContent=s.title;$('#chapter-copy').textContent=s.copy;$('#knowledge').textContent=s.knowledge;$('#scale-note').textContent=s.scale;$('#next').textContent=s.action+' ↗';$('.field-panel').scrollTop=0;
 document.querySelectorAll('[data-stage]').forEach(b=>{if(Number(b.dataset.stage)===stage)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
 cosmos?.setView(s.view,calm);cosmos?.setLocator(false);
 $('#chapter-content').replaceChildren();$('#interaction-hint').textContent=cosmos?'Sleep om te kijken · scroll of knijp om te zoomen':'Zonder 3D: volg de teksten, foto en bewijskaarten.';
 if(stage===0){$('#chapter-content').innerHTML='<button id="locate-moon" aria-pressed="false">Waar is Enceladus?</button><p class="micro" id="locator-note" hidden>De markering is vergroot, de maan niet. Circa 238.000 km van Saturnus’ middelpunt. De baanfase is geënsceneerd; niet de positie van vandaag.</p>';$('#locate-moon').onclick=e=>{const active=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(active));$('#locator-note').hidden=!active;cosmos?.setLocator(active);};}
 if(stage===1){$('#chapter-content').innerHTML='<label class="range-label">Kijkhoek boven het ringvlak <output id="ring-value">14°</output><input id="ring-angle" type="range" min="3" max="80" value="14"></label><p class="micro">De lichtblauwe referentiestaaf is één lokale modeleeneenheid. Het is géén meting van echte brokstukken. Grootte en dichtheid zijn gekozen om het principe te laten zien.</p><p class="micro">Hier zie je de heldere hoofdringen. Enceladus bevindt zich verder weg, in de veel ijlere E-ring.</p>';$('#ring-angle').oninput=e=>{$('#ring-value').textContent=e.target.value+'°';cosmos?.ringAngle(e.target.value);};}
 if(stage===2){$('#chapter-content').innerHTML='<label class="range-label">Lichthoek <output id="phase-value">35° · frontaal licht</output><input id="phase" type="range" min="5" max="170" value="35"></label><p class="micro">Stuur het licht rond de maan. Het effect is kwalitatief, niet een gekalibreerde helderheidsmeting. Met vrij draaien verandert ook je kijkhoek.</p><button id="photo-open">Bekijk de echte Cassini-foto ↗</button>';cosmos?.setPhase(35);$('#phase').oninput=e=>{const n=Number(e.target.value);$('#phase-value').textContent=n+'° · '+(n>125?'tegenlicht':n>65?'zijlicht':'frontaal licht');cosmos?.setPhase(n);};$('#photo-open').onclick=()=>$('#photo').showModal();}
 if(stage===3){$('#chapter-content').innerHTML=`<div class="evidence-tabs" role="group" aria-label="Kies een bewijskaart">${evidence.map((e,i)=>`<button data-evidence="${i}" aria-pressed="false">${e.name}</button>`).join('')}</div><div id="evidence-detail"></div><details class="interpretation"><summary>Twee mogelijke lezingen</summary><p><b>Een verklaring zonder leven.</b> Water, fosfaten en chemische energie kunnen ook zonder biologie bestaan.</p><p><b>Een verklaring waarin leven bijdraagt.</b> De omstandigheden zijn interessant, maar de gemeten stoffen alleen onderscheiden deze lezing niet van de eerste. Dit zijn niet twee bewezen of even waarschijnlijke uitkomsten.</p><p>Welke extra waarneming zou dat verschil wél kunnen maken?</p></details>`;document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{card=Number(b.dataset.evidence);evidenceCard();});evidenceCard();}
 if(stage===4){$('#chapter-content').innerHTML='<div class="choice-list"><button id="investigate">Verder onderzoeken</button><button id="stay">Hier blijven kijken</button><a class="choice-link" href="explore.html?body=Earth">Terugkijken naar de Aarde ↗</a></div><details class="interpretation"><summary>Een ongemakkelijke vervolgvraag</summary><p>Dichter onderzoeken: wat wil je kunnen onderscheiden? Stel dat een toekomstige missie in de oceaan kan bemonsteren, maar daardoor ook materiaal van de Aarde kan binnenbrengen. Dat verstoringsrisico is een aanname van dit gedachte-experiment, geen voorspelling van een echte missie.</p><label>Mijn onderzoeksvraag<select id="research-question"><option>Welke chemie kan zonder leven ontstaan?</option><option>Hoe bereikt oceaanmateriaal de pluim?</option><option>Welke combinatie van aanwijzingen past bij leven?</option></select></label><p>Kies een benadering en bekijk wat die wel en niet oplevert.</p><div class="choice-list"><button data-approach="close">Dichter bemonsteren</button><button data-approach="watch">Op afstand blijven waarnemen</button><button data-approach="wait">Voorlopig stoppen</button></div><p id="approach-result" role="status"></p><button id="save-question">Bewaar mijn vraag</button></details>';$('#investigate').onclick=()=>setStage(3);$('#stay').onclick=()=>immerse(true);let approach='Nog geen benadering gekozen.';const approaches={close:'Dichter bemonsteren kan de samenstelling directer onderzoeken. De herkomst en betekenis van stoffen blijven interpretatie vragen; in dit scenario aanvaard je meer verstoringsrisico. Ook een lege monstername bewijst niet dat de hele oceaan levenloos is.',watch:'Langer op afstand waarnemen kan variatie in pluimen en samenstelling helpen herkennen. Je beperkt direct contact, maar blijft afhankelijk van wat de oceaan naar buiten brengt en wat instrumenten kunnen zien.',wait:'Voorlopig stoppen voorkomt extra ingrepen door deze denkbeeldige missie en geeft ruimte voor betere methoden. De onzekerheid blijft; mogelijk stel je waardevolle kennis uit.'};document.querySelectorAll('[data-approach]').forEach(b=>b.onclick=()=>{approach=approaches[b.dataset.approach];$('#approach-result').textContent=approach;document.querySelectorAll('[data-approach]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});$('#save-question').onclick=()=>{record({id:'question-'+Date.now(),title:'Mijn vervolgvraag · gedachte-experiment',text:$('#research-question').value+'\n'+approach,source:''});$('#save-question').textContent='Vraag toegevoegd';};}
 $('#next').onclick=()=>stage===4?openJournal():setStage(stage+1);
}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>setStage(b.dataset.stage));
addEventListener('hashchange',()=>setStage(location.hash.slice(1),false));
const photo=document.createElement('dialog');photo.id='photo';photo.innerHTML='<form method="dialog"><button class="close">Sluiten ×</button></form><p class="kicker">● ECHTE MISSIE-OPNAME</p><h2>De nacht geeft licht.</h2><img src="assets/PIA14599-plume.jpg" alt="Cassini-foto: een smalle verlichte rand van Enceladus en zwakke ijspluimen onder de donkere zuidpool." width="958" height="965" loading="lazy"><p>Cassini · 20 februari 2012 · fasehoek 165°. Kleine ijsdeeltjes worden in tegenlicht zichtbaar. De 3D-pluim in de app is een reconstructie, niet een omzetting van deze foto naar exacte diepte.</p><p class="micro">NASA/JPL-Caltech/Space Science Institute · <a href="https://science.nasa.gov/resource/dark-moon-dramatic-plume/" target="_blank" rel="noopener noreferrer">PIA14599 en originele toelichting ↗</a></p>';document.body.append(photo);photo.querySelector('img').onerror=()=>{photo.querySelector('img').hidden=true;const p=document.createElement('p');p.textContent='De foto kon niet laden. Open de originele toelichting via de link hieronder.';photo.prepend(p);};

// Optional synthesized ambience, never called recordings of space or scientific sonification.
let audio=null,shipGain=null,musicGain=null;
const sound=document.createElement('section');sound.innerHTML='<h3>Geluid, als je dat wilt</h3><p>Zelfgemaakte klanksfeer, geen opname van ruimtegeluid of meetdata. Alle ontdekkingen werken ook in stilte.</p><button id="audio-toggle" aria-pressed="false">Klanksfeer aan</button><label class="range-label">Schip<input id="ship-volume" type="range" min="0" max="100" value="25"></label><label class="range-label">Muzikale laag<input id="music-volume" type="range" min="0" max="100" value="20"></label><p class="micro" id="audio-status" role="status"></p>';$('#settings').insertBefore(sound,$('#source-list'));
function volume(){if(!audio)return;shipGain.gain.setTargetAtTime(Number($('#ship-volume').value)/100*.06,audio.currentTime,.3);musicGain.gain.setTargetAtTime(Number($('#music-volume').value)/100*.035,audio.currentTime,.3);}
$('#audio-toggle').onclick=async()=>{
 try{
  if(!audio){audio=new AudioContext();shipGain=audio.createGain();musicGain=audio.createGain();shipGain.gain.value=0;musicGain.gain.value=0;shipGain.connect(audio.destination);musicGain.connect(audio.destination);for(const [frequency,gain] of [[49,shipGain],[51,shipGain],[147,musicGain],[220.5,musicGain],[294,musicGain]]){const oscillator=audio.createOscillator();oscillator.type='sine';oscillator.frequency.value=frequency;oscillator.connect(gain);oscillator.start();}await audio.resume();volume();}
  else if(audio.state==='running')await audio.suspend();else{await audio.resume();volume();}
  const playing=audio.state==='running';$('#audio-toggle').textContent=playing?'Alles stil':'Klanksfeer aan';$('#audio-toggle').setAttribute('aria-pressed',String(playing));
 }catch{$('#audio-status').textContent='Geluid is hier niet beschikbaar. Je kunt de volledige expeditie zonder geluid volgen.';}
};
$('#ship-volume').oninput=volume;$('#music-volume').oninput=volume;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&audio?.state==='running'){audio.suspend();$('#audio-toggle').textContent='Klanksfeer aan';$('#audio-toggle').setAttribute('aria-pressed','false');}});
addEventListener('pagehide',event=>{if(!event.persisted){cosmos?.dispose();audio?.close();}});
setStage(stage,false);
